### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [iadvize/integration-gtm-main-tool#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) encodeUriComponent should be used on user provided values that are then used as parameters in your url. These methods take in a single text argument and return a URI Encoded string. You should use this method on data.sid and data.lang when generating the url
'https://'+data.hostname+'/iadvize.js?sid='+data.sid+(data.lang ? '&lang='+data.lang
2) encodeUri should be used on user provided values that are then used as path values to create your url. Returns an encoded Uniform Resource Identifier (URI) by escaping special characters. Returns a string that represents the provided string encoded as a URI. You should use this method on data.hostname when generating the url
'https://'+data.hostname+'/iadvize.js?sid='+data.sid+(data.lang ? '&lang='+data.lang

**Comment by eroak** [comment]
Thank you for your review @praveena-pappu

I didn't use "encodeURIComponent" because the user can't choose other values than those specified in a drop-down list (for the lang and hostname parameters) and for the SID parameter it is necessarily an integer value.

Should I still add "encodeURIComponent"?

**Comment by praveena-pappu** [comment]
Hello,

Please use [encodeUriComponent](https://developers.google.com/tag-manager/templates/api/#encodeuricomponent) on the input values that are then used in creating the url. Also please use [encodeURI](https://developers.google.com/tag-manager/templates/api/#encodeuri) for uri.

**Comment by eroak** [comment]
Hello @praveena-pappu 

I added [encodeUriComponent](https://developers.google.com/tag-manager/templates/api/#encodeuricomponent) for each element of the URL.

**Comment by eroak** [comment]
Hello @praveena-pappu , is it ok for you now ?

**Comment by eroak** [comment]
Template approved ✅ Thank you @praveena-pappu 👍
